### PR TITLE
[George] my changed in george branch to main branch

### PR DESCRIPTION
**Pull request by George-Sucuzhanay**

### CODE REVIEW

**Comment by George-Sucuzhanay** [comment]
These are my changes for your project. Let me know what you think. Thanks!

**Comment by Alexander-col** [comment]
I like the changes that were made and it offers my a new perspective on how the same task can be completed in diffrent ways.

**Comment by George-Sucuzhanay** [comment]
Great ready to merge now! wow!

**Comment by Alexander-col** [comment]
that more comments can be put into code so that we don't get lost diving into our old code!

**Pull request merged**
